// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/CelestialWinterMarketPoster-lFu0hi/HolidayMarket.tsx": () => import("../components/mockups/templates/CelestialWinterMarketPoster-lFu0hi/HolidayMarket.tsx"),
  "./components/mockups/templates/MissionControlBentoDashboard-NoVcFf/Dashboard.tsx": () => import("../components/mockups/templates/MissionControlBentoDashboard-NoVcFf/Dashboard.tsx")
};
